# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - revive
    - misspell
    - prealloc
    - nolintlint
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - forbidigo
    - makezero
    - nilerr
    - predeclared
    - usetesting
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment    # noisy, low-value for this project
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam          # Temporal workflow params are value types by design
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: var-declaration
      - name: var-naming
  misspell:
    locale: US
  forbidigo:
    forbid:
      - p: ^fmt\.Print
        msg: "Use log/slog for output, not fmt.Print"
      - p: ^os\.Exit
        msg: "Use log.Fatal or return errors instead of os.Exit (except in main)"

issues:
  exclude-rules:
    # Allow fmt.Print in main packages
    - path: cmd/
      linters:
        - forbidigo
    # Allow os.Exit in main
    - path: cmd/cortex/main\.go
      linters:
        - forbidigo
    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam
  max-issues-per-linter: 50
  max-same-issues: 10
